# Generated by Django 4.2 on 2024-04-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zutomayoCardSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.IntegerField(verbose_name='カードID')),
                ('image', models.ImageField(upload_to='', verbose_name='画像')),
                ('name', models.CharField(max_length=255, verbose_name='カード名')),
                ('rare', models.CharField(null=True, verbose_name='レア度')),
                ('cardType', models.CharField(max_length=255, verbose_name='カードタイプ')),
                ('element', models.CharField(max_length=255, verbose_name='属性')),
                ('kronos', models.IntegerField(verbose_name='クロノス')),
                ('powerCost', models.IntegerField(verbose_name='コスト')),
                ('sendToPower', models.IntegerField(default=0, verbose_name='SToP')),
                ('nightPower', models.IntegerField(null=True, verbose_name='NIGHT')),
                ('dayPower', models.IntegerField(null=True, verbose_name='DAY')),
                ('skillText', models.TextField(max_length=255, null=True, verbose_name='能力')),
                ('skillType', models.CharField(max_length=255, null=True, verbose_name='能力タイプ')),
            ],
        ),
    ]
