# Generated by Django 4.2 on 2024-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zutomayoCardSearch', '0002_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dayPower',
            field=models.IntegerField(blank=True, null=True, verbose_name='DAY'),
        ),
        migrations.AlterField(
            model_name='card',
            name='nightPower',
            field=models.IntegerField(blank=True, null=True, verbose_name='NIGHT'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rare',
            field=models.CharField(verbose_name='レア度'),
        ),
        migrations.AlterField(
            model_name='card',
            name='skillText',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='能力'),
        ),
        migrations.AlterField(
            model_name='card',
            name='skillType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='能力タイプ'),
        ),
    ]
